//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSImageView, NSString, NSTextField;

@interface AboutWindowController : NSWindowController <NSWindowDelegate>
{
    NSTextField *_lblVersion;
    NSTextField *_lblLicenseType;
    NSTextField *_txtLicenseType;
    NSTextField *_lblRegisteredTo;
    NSTextField *_txtRegisteredTo;
    NSTextField *_lblEltimaSign;
    NSImageView *_imgLogo;
}

@property NSTextField *lblEltimaSign; // @synthesize lblEltimaSign=_lblEltimaSign;
@property NSTextField *txtRegisteredTo; // @synthesize txtRegisteredTo=_txtRegisteredTo;
@property NSTextField *lblRegisteredTo; // @synthesize lblRegisteredTo=_lblRegisteredTo;
@property NSTextField *txtLicenseType; // @synthesize txtLicenseType=_txtLicenseType;
@property NSTextField *lblLicenseType; // @synthesize lblLicenseType=_lblLicenseType;
@property NSTextField *lblVersion; // @synthesize lblVersion=_lblVersion;
@property NSImageView *imgLogo; // @synthesize imgLogo=_imgLogo;
- (void)updateActivationInfo;
- (void)windowDidLoad;
- (id)initWithWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

