//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class CustomCursorButton, NSButton, NSImageView, NSTextField, PatternBackgroundView, YDHorizontalLine;

@interface ActivationWindowController : NSWindowController
{
    NSButton *_btnBuyNow;
    NSButton *_btnCancel;
    NSButton *_btnActivate;
    NSTextField *_txtActivationCode;
    NSTextField *_txtActivationInfo;
    NSTextField *_lblEnterActivationCode;
    NSImageView *_imgLogo;
    PatternBackgroundView *_rightSideView;
    YDHorizontalLine *_bottomHorizontalLine;
    YDHorizontalLine *_rightVerticalLine;
    CustomCursorButton *_btnLostCode;
}

@property NSButton *btnActivate; // @synthesize btnActivate=_btnActivate;
@property NSButton *btnCancel; // @synthesize btnCancel=_btnCancel;
@property NSButton *btnBuyNow; // @synthesize btnBuyNow=_btnBuyNow;
@property CustomCursorButton *btnLostCode; // @synthesize btnLostCode=_btnLostCode;
@property YDHorizontalLine *rightVerticalLine; // @synthesize rightVerticalLine=_rightVerticalLine;
@property YDHorizontalLine *bottomHorizontalLine; // @synthesize bottomHorizontalLine=_bottomHorizontalLine;
@property PatternBackgroundView *rightSideView; // @synthesize rightSideView=_rightSideView;
@property NSImageView *imgLogo; // @synthesize imgLogo=_imgLogo;
@property NSTextField *lblEnterActivationCode; // @synthesize lblEnterActivationCode=_lblEnterActivationCode;
@property NSTextField *txtActivationInfo; // @synthesize txtActivationInfo=_txtActivationInfo;
@property NSTextField *txtActivationCode; // @synthesize txtActivationCode=_txtActivationCode;
- (BOOL)checkIsValidKey:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)customizingAppearance;
- (void)btnActivateAiryClick:(id)arg1;
- (void)btnCancelClick:(id)arg1;
- (void)btnBuyNowClick:(id)arg1;
- (void)btnLostCodeClick:(id)arg1;
- (void)windowDidLoad;
- (id)initWithWindow:(id)arg1;

@end

