//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface aHelper : NSObject
{
}

+ (id)getHardwareID;
+ (id)hddSerialNumber;
+ (id)computerSerialNumber;
+ (id)encrypt:(id)arg1 key:(id)arg2;
+ (id)urlLenCode:(id)arg1;
+ (id)_encrypt:(id)arg1 key:(id)arg2;
+ (id)toByteArray:(id)arg1 includeLength:(BOOL)arg2;
+ (id)toIntArray:(id)arg1 includeLength:(BOOL)arg2;

@end

