//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSTextField, PatternBackgroundView, YDHorizontalLine;

@interface DemoReminderWindowController : NSWindowController
{
    NSButton *btnFreeMode;
    NSButton *btnActivate;
    NSButton *btnBuyNow;
    NSTextField *lblPrice;
    NSTextField *lblTrademark;
    NSTextField *lblCountFreeDownloads;
    NSTextField *lblActivateAiry;
    PatternBackgroundView *rightSideView;
    YDHorizontalLine *bottomLine;
    YDHorizontalLine *rightLine;
    NSTextField *txtTrademark;
    NSTextField *txtPrice;
}

@property YDHorizontalLine *rightLine; // @synthesize rightLine;
@property YDHorizontalLine *bottomLine; // @synthesize bottomLine;
@property PatternBackgroundView *rightSideView; // @synthesize rightSideView;
@property NSTextField *lblActivateAiry; // @synthesize lblActivateAiry;
@property NSTextField *lblCountFreeDownloads; // @synthesize lblCountFreeDownloads;
@property NSTextField *lblTrademark; // @synthesize lblTrademark;
@property NSTextField *lblPrice; // @synthesize lblPrice;
@property NSButton *btnBuyNow; // @synthesize btnBuyNow;
@property NSButton *btnActivate; // @synthesize btnActivate;
@property NSButton *btnFreeMode; // @synthesize btnFreeMode;
- (void)customizingAppearance;
- (void)buttonBuyNowWasClicked:(id)arg1;
- (void)buttonActivateWasClicked:(id)arg1;
- (void)buttonContinueFreeWasClicked:(id)arg1;
- (void)windowDidLoad;

@end

