//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@class NSTrackingArea;

@interface DownloadsTableRowView : NSTableRowView
{
    NSTrackingArea *trackingArea;
    long long rowIndex;
    BOOL mouseInside;
    BOOL hideBtnStartStopFind;
    BOOL hideBtnCancelDelete;
}

@property BOOL hideBtnCancelDelete; // @synthesize hideBtnCancelDelete;
@property BOOL hideBtnStartStopFind; // @synthesize hideBtnStartStopFind;
@property long long rowIndex; // @synthesize rowIndex;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)ensureTrackingArea;
@property BOOL mouseInside; // @synthesize mouseInside;
- (void)dealloc;

@end

