//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSButton, NSProgressIndicator, NSTextField, RoundedCornerImageView, RoundedCornerView, YDProgressView;

@interface DownloadsTableCellView : NSTableCellView
{
    RoundedCornerView *mainView;
    RoundedCornerImageView *thumbnail;
    YDProgressView *progressView;
    NSTextField *txtTitle;
    NSTextField *txtInformation;
    NSProgressIndicator *progressIndicator;
    NSButton *btnStartStopFind;
    NSButton *btnCancelDelete;
}

@property NSButton *btnCancelDelete; // @synthesize btnCancelDelete;
@property NSButton *btnStartStopFind; // @synthesize btnStartStopFind;
@property NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
@property NSTextField *txtInformation; // @synthesize txtInformation;
@property NSTextField *txtTitle; // @synthesize txtTitle;
@property YDProgressView *progressView; // @synthesize progressView;
@property RoundedCornerImageView *thumbnail; // @synthesize thumbnail;
@property RoundedCornerView *mainView; // @synthesize mainView;
- (void)viewWillDraw;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

