//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@interface DSImagePopUpButton : NSPopUpButton
{
}

+ (Class)cellClass;
- (id)rightDisabledImage;
- (void)setRightDisabledImage:(id)arg1;
- (id)fillDisabledImage;
- (void)setFillDisabledImage:(id)arg1;
- (id)leftDisabledImage;
- (void)setLeftDisabledImage:(id)arg1;
- (id)rightPressedImage;
- (void)setRightPressedImage:(id)arg1;
- (id)fillPressedImage;
- (void)setFillPressedImage:(id)arg1;
- (id)leftPressedImage;
- (void)setLeftPressedImage:(id)arg1;
- (id)rightImage;
- (void)setRightImage:(id)arg1;
- (id)fillImage;
- (void)setFillImage:(id)arg1;
- (id)leftImage;
- (void)setLeftImage:(id)arg1;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (id)initWithCoder:(id)arg1;

@end

