//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Localizer : NSObject
{
}

+ (void)localizeMenu:(id)arg1 withName:(id)arg2 inTable:(id)arg3;
+ (void)_localizeMenuItem:(id)arg1 withName:(id)arg2 inTable:(id)arg3;
+ (id)dontAskAgainButtonTitle;
+ (id)dontShowAgainButtonTitle;
+ (id)openButtonTitle;
+ (id)noButtonTitle;
+ (id)yesButtonTitle;
+ (id)cancelButtonTitle;
+ (id)okButtonTitle;
+ (id)localizedStringForKey:(id)arg1 inTable:(id)arg2;
+ (id)nonlocalizedStringForKey:(id)arg1 inTable:(id)arg2;
+ (id)nonLocalizedStringForKey:(id)arg1;
+ (id)localizedStringForKey:(id)arg1;
+ (id)nativBundle;
+ (void)cleanNativBundle;
- (id)init;

@end

