//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (HexDump)
- (id)hexdump;
- (id)hexval;
- (id)decodeBase64WithNewLines:(BOOL)arg1;
- (id)decodeBase64;
- (id)encodeBase64WithNewlines:(BOOL)arg1;
- (id)encodeBase64;
@end

