//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class DownloadItem, MainWindowController, NSString;

@interface OperationLinkUpdating : NSOperation
{
    MainWindowController *_controller;
    DownloadItem *_item;
    NSString *_pageUrl;
}

@property(retain) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(retain) DownloadItem *item; // @synthesize item=_item;
@property(retain) MainWindowController *controller; // @synthesize controller=_controller;
- (void)main;
- (id)initOperationForDownloadItem:(id)arg1 forController:(id)arg2;
- (void)dealloc;

@end

