//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MainWindowController, NSString;

@interface OperationReceivingLinksOfPlaylist : NSOperation
{
    MainWindowController *_controller;
    NSString *_pageUrl;
    unsigned long long _currentLinksNumber;
}

@property unsigned long long currentLinksNumber; // @synthesize currentLinksNumber=_currentLinksNumber;
@property(retain) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(retain) MainWindowController *controller; // @synthesize controller=_controller;
- (void)main;
- (id)initOperationForPlaylist:(id)arg1 forController:(id)arg2 currentLinksNumber:(unsigned long long)arg3;
- (void)dealloc;

@end

