//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MainWindowController, NSArray;

@interface OperationReceivingLinksOfVideo : NSOperation
{
    MainWindowController *_controller;
    NSArray *_urls;
}

@property(retain) NSArray *urls; // @synthesize urls=_urls;
@property(retain) MainWindowController *controller; // @synthesize controller=_controller;
- (unsigned long long)getResolutionFromString:(id)arg1 forItag:(int)arg2;
- (void)getEstimatedSizeForItem:(id)arg1;
- (void)main;
- (void)dealloc;
- (id)initOperationForVideos:(id)arg1 forController:(id)arg2;

@end

