//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class DownloadItem, MainWindowController, NSData;

@interface OperationSavingOfDataSegments : NSOperation
{
    MainWindowController *_controller;
    DownloadItem *_item;
    NSData *_data;
    int _kindOfItem;
    long long _expectedBytes;
}

@property(nonatomic) long long expectedBytes; // @synthesize expectedBytes=_expectedBytes;
@property(retain, nonatomic) MainWindowController *controller; // @synthesize controller=_controller;
@property(nonatomic) int kindOfItem; // @synthesize kindOfItem=_kindOfItem;
@property(retain, nonatomic) DownloadItem *item; // @synthesize item=_item;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void)main;
- (id)initWithData:(id)arg1 forItem:(id)arg2 type:(int)arg3 andController:(id)arg4;
- (void)dealloc;

@end

