//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class DownloadItem, MainWindowController, NSData;

@interface OperationOfSavingData : NSOperation
{
    NSData *_data;
    DownloadItem *_item;
    MainWindowController *_controller;
    BOOL _isLastOperation;
}

@property(nonatomic) BOOL isLastOperation; // @synthesize isLastOperation=_isLastOperation;
@property(retain, nonatomic) MainWindowController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) DownloadItem *item; // @synthesize item=_item;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void)handlingExceptions:(id)arg1;
- (id)initWithData:(id)arg1 forItem:(id)arg2 andController:(id)arg3;
- (void)dealloc;

@end

