//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@interface PageUrlTextView : NSTextView
{
    id <MouseDownTextFieldDelegate> delegate;
}

@property id <MouseDownTextFieldDelegate> delegate; // @synthesize delegate;
- (void)mouseDown:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setPlaceholderString:(id)arg1;
- (void)enableTextView:(BOOL)arg1;
- (BOOL)isEnabled;
- (void)doCommandBySelector:(SEL)arg1;
- (void)paste:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)initializePlaceholder;
- (id)initWithFrame:(struct CGRect)arg1;

@end

