//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSImage, NSString;

@interface PatternBackgroundView : NSView
{
    NSString *_backImageName;
    NSImage *_leftImage;
    NSImage *_fillImage;
    NSImage *_rightImage;
    NSColor *_backColor;
}

@property(retain, nonatomic) NSColor *backColor; // @synthesize backColor=_backColor;
@property(retain, nonatomic) NSImage *rightImage; // @synthesize rightImage=_rightImage;
@property(retain, nonatomic) NSImage *fillImage; // @synthesize fillImage=_fillImage;
@property(retain, nonatomic) NSImage *leftImage; // @synthesize leftImage=_leftImage;
@property(retain, nonatomic) NSString *backImageName; // @synthesize backImageName=_backImageName;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

