//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSProgressIndicator, NSTextField;

@interface ProcessingLinksWindowController : NSWindowController
{
    NSTextField *txtAboutProcessing;
    NSProgressIndicator *progressProcessing;
    NSButton *btnCancel;
}

@property NSButton *btnCancel; // @synthesize btnCancel;
@property NSProgressIndicator *progressProcessing; // @synthesize progressProcessing;
@property NSTextField *txtAboutProcessing; // @synthesize txtAboutProcessing;
- (void)buttonCancelWasClicked:(id)arg1;
- (void)windowDidLoad;
- (id)initWithWindow:(id)arg1;

@end

