//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSImageView, NSTextField;

@interface WelcomeScreenWindowController : NSWindowController
{
    id eventMonitor;
    NSButton *btnContinue;
    NSTextField *lblEasyDownloadHead;
    NSTextField *lblEasyDownloadText;
    NSTextField *lblTypeResolutionHead;
    NSTextField *lblTypeResolutionText;
    NSTextField *lblStartPauseHead;
    NSTextField *lblStartPauseText;
    NSTextField *lblExtractAudioHead;
    NSTextField *lblExtractAudioText;
    NSTextField *lblPlaylistChannelHead;
    NSTextField *lblPlaylistChannelText;
    NSImageView *imgEasyDownload;
    NSImageView *imgTypeResolution;
    NSImageView *imgStartPause;
    NSImageView *imgExtractAudio;
    NSImageView *imgPlaylistChannel;
}

@property NSTextField *lblPlaylistChannelText; // @synthesize lblPlaylistChannelText;
@property NSTextField *lblPlaylistChannelHead; // @synthesize lblPlaylistChannelHead;
@property NSTextField *lblExtractAudioText; // @synthesize lblExtractAudioText;
@property NSTextField *lblExtractAudioHead; // @synthesize lblExtractAudioHead;
@property NSTextField *lblStartPauseText; // @synthesize lblStartPauseText;
@property NSTextField *lblStartPauseHead; // @synthesize lblStartPauseHead;
@property NSTextField *lblTypeResolutionText; // @synthesize lblTypeResolutionText;
@property NSTextField *lblTypeResolutionHead; // @synthesize lblTypeResolutionHead;
@property NSTextField *lblEasyDownloadText; // @synthesize lblEasyDownloadText;
@property NSTextField *lblEasyDownloadHead; // @synthesize lblEasyDownloadHead;
@property NSImageView *imgPlaylistChannel; // @synthesize imgPlaylistChannel;
@property NSImageView *imgExtractAudio; // @synthesize imgExtractAudio;
@property NSImageView *imgStartPause; // @synthesize imgStartPause;
@property NSImageView *imgTypeResolution; // @synthesize imgTypeResolution;
@property NSImageView *imgEasyDownload; // @synthesize imgEasyDownload;
@property NSButton *btnContinue; // @synthesize btnContinue;
- (void)customizingAppearance;
- (void)buttonContinueWasClicked:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;

@end

