//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YDActivation : NSObject
{
}

+ (BOOL)isPreviousTrialKey:(id)arg1;
+ (BOOL)isPreviousDemoKey:(id)arg1;
+ (void)setActivationCode:(id)arg1 silentMode:(BOOL)arg2 asyncMode:(BOOL)arg3;
+ (void)setActivationCode:(id)arg1 silentMode:(BOOL)arg2;
+ (void)setActivationCode:(id)arg1;

@end

