//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBox.h"

@class NSColor;

@interface YDHorizontalLine : NSBox
{
    NSColor *_lineColor;
    double _lineWidth;
    BOOL _withShadow;
    BOOL _isDashed;
    double _dashWidth;
    double _dashDistance;
    BOOL _isHorizontal;
}

@property(nonatomic) BOOL isHorizontal; // @synthesize isHorizontal=_isHorizontal;
@property(nonatomic) double dashDistance; // @synthesize dashDistance=_dashDistance;
@property(nonatomic) double dashWidth; // @synthesize dashWidth=_dashWidth;
@property(nonatomic) BOOL isDashed; // @synthesize isDashed=_isDashed;
@property(nonatomic) BOOL withShadow; // @synthesize withShadow=_withShadow;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) NSColor *lineColor; // @synthesize lineColor=_lineColor;
- (void)drawRect:(struct CGRect)arg1;

@end

