//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YDUserDefaults : NSObject
{
}

+ (BOOL)loggingIsEnabled;
+ (void)resetAllDontAskMeAgainOptions;
+ (BOOL)allowsSendStatistics;
+ (void)setYoutubeSubtitleFormat:(id)arg1;
+ (id)youtubeSubtitlesFormat;
+ (void)setOptionDontAskAgainLogInYoutube:(BOOL)arg1;
+ (BOOL)optionDontAskAgainLogInYoutube;
+ (void)setLoggedInYoutube:(BOOL)arg1;
+ (BOOL)loggedInYoutube;
+ (void)setOptionRememberChoiceForVideoPartOfPlaylist:(BOOL)arg1;
+ (BOOL)optionRememberChoiceForVideoPartOfPlaylist;
+ (void)setChoiceDownloadCompletePlaylistOrVideoOnly:(long long)arg1;
+ (long long)choiceDownloadCompletePlaylistOrVideoOnly;
+ (void)setOptionDontAskAgainWhenAppTerminated:(BOOL)arg1;
+ (BOOL)optionDontAskAgainWhenAppTerminated;
+ (void)setOptionDontShowAgainWhenUpdateError:(BOOL)arg1;
+ (BOOL)optionDontShowAgainWhenUpdateError;
+ (void)setOptionDontShowAgainWhenFailedConnection:(BOOL)arg1;
+ (BOOL)optionDontShowAgainWhenFailedConnection;
+ (void)setOptionDontAskAgainCancelDownloads:(BOOL)arg1;
+ (BOOL)optionDontAskAgainCancelDownloads;
+ (void)setLastSelectedFormatResolution:(id)arg1;
+ (id)lastSelectedFormatResolution;
+ (void)setDownloadsList:(id)arg1;
+ (id)downloadsList;
+ (void)setCurrentUserPreferences:(id)arg1;
+ (id)currentUserPreferences;
+ (void)setNumberOfDownloadsFreeVersion:(long long)arg1;
+ (long long)numberOfDownloadsFreeVersion;
+ (void)setWelcomeScreenShown:(BOOL)arg1;
+ (BOOL)welcomeScreenShown;
+ (void)setInstallationSource:(id)arg1;
+ (id)installationSource;
+ (void)setPurchaseLicenseLink:(id)arg1;
+ (id)purchaseLicenseLink;
+ (void)setWasPurchasedPreviously:(BOOL)arg1;
+ (BOOL)wasPurchasedPreviously;
+ (void)setLicenseName:(id)arg1;
+ (id)licenseName;
+ (void)setRegisteredName:(id)arg1;
+ (id)registeredName;
+ (void)setActivationKey:(id)arg1;
+ (id)activationKey;
+ (void)setNoticeOfThirdPartyCopyright:(BOOL)arg1;
+ (BOOL)noticeOfThirdPartyCopyright;
+ (void)initialize;

@end

