//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSAlertDelegate.h"
#import "NSApplicationDelegate.h"
#import "NSUserNotificationCenterDelegate.h"

@class AboutWindowController, ActivationWindowController, DemoReminderWindowController, LoginYoutubeWindowController, MainWindowController, NSMutableArray, NSString, OfferReminderWindowController, PreferencesWindowController, WelcomeScreenWindowController;

@interface YoutubeDownloaderAppDelegate : NSObject <NSApplicationDelegate, NSAlertDelegate, NSUserNotificationCenterDelegate>
{
    MainWindowController *_mainWindowController;
    ActivationWindowController *_activationWindow;
    LoginYoutubeWindowController *_loginWindow;
    PreferencesWindowController *_preferencesWindow;
    AboutWindowController *_aboutWindow;
    DemoReminderWindowController *_demoreminderWindow;
    OfferReminderWindowController *_offerriminderWindow;
    WelcomeScreenWindowController *_welcomeScreen;
    double _defaultPrice;
    double _currentPrice;
    NSString *_dataFile1;
    BOOL _logIsEnabled;
    NSString *_pathToAiryLogFile;
    NSString *_pathToLogFile;
    NSMutableArray *_downloadsList;
    BOOL _isDemoVersion;
    BOOL _isProVersion;
    BOOL _wasPurchased;
    int _activationErrorCode;
    int _maxFreeDownloads;
    int _keyType;
    int _daysLeft;
    NSString *_cookies;
    NSString *_bookmarkUrl;
    BOOL _appTermination;
    NSMutableArray *_tasksExtractions;
    BOOL alertReactivationAlreadyShown;
    NSString *purchaseLink;
    NSString *installSource;
}

@property(retain, nonatomic) NSString *purchaseLink; // @synthesize purchaseLink;
@property(nonatomic) BOOL wasPurchased; // @synthesize wasPurchased=_wasPurchased;
@property(retain, nonatomic) NSMutableArray *tasksExtractions; // @synthesize tasksExtractions=_tasksExtractions;
@property(nonatomic) BOOL appTermination; // @synthesize appTermination=_appTermination;
@property(retain, nonatomic) NSString *bookmarkUrl; // @synthesize bookmarkUrl=_bookmarkUrl;
@property(retain) NSString *cookies; // @synthesize cookies=_cookies;
@property(nonatomic) int daysLeft; // @synthesize daysLeft=_daysLeft;
@property(nonatomic) int keyType; // @synthesize keyType=_keyType;
@property(nonatomic) int maxFreeDownloads; // @synthesize maxFreeDownloads=_maxFreeDownloads;
@property(nonatomic) int activationErrorCode; // @synthesize activationErrorCode=_activationErrorCode;
@property(nonatomic) BOOL isProVersion; // @synthesize isProVersion=_isProVersion;
@property(nonatomic) BOOL isDemoVersion; // @synthesize isDemoVersion=_isDemoVersion;
@property(retain, nonatomic) NSMutableArray *downloadsList; // @synthesize downloadsList=_downloadsList;
@property(retain, nonatomic) NSString *pathToLogFile; // @synthesize pathToLogFile=_pathToLogFile;
@property(retain, nonatomic) NSString *pathToAiryLogFile; // @synthesize pathToAiryLogFile=_pathToAiryLogFile;
@property(nonatomic) BOOL logIsEnabled; // @synthesize logIsEnabled=_logIsEnabled;
@property(retain, nonatomic) NSString *dataFile1; // @synthesize dataFile1=_dataFile1;
@property(nonatomic) double currentPrice; // @synthesize currentPrice=_currentPrice;
@property(nonatomic) double defaultPrice; // @synthesize defaultPrice=_defaultPrice;
@property(retain, nonatomic) WelcomeScreenWindowController *welcomeScreen; // @synthesize welcomeScreen=_welcomeScreen;
@property(retain, nonatomic) OfferReminderWindowController *offerriminderWindow; // @synthesize offerriminderWindow=_offerriminderWindow;
@property(retain, nonatomic) DemoReminderWindowController *demoreminderWindow; // @synthesize demoreminderWindow=_demoreminderWindow;
@property(retain, nonatomic) AboutWindowController *aboutWindow; // @synthesize aboutWindow=_aboutWindow;
@property(retain, nonatomic) PreferencesWindowController *preferencesWindow; // @synthesize preferencesWindow=_preferencesWindow;
@property(retain, nonatomic) LoginYoutubeWindowController *loginWindow; // @synthesize loginWindow=_loginWindow;
@property(retain, nonatomic) ActivationWindowController *activationWindow; // @synthesize activationWindow=_activationWindow;
@property(retain, nonatomic) MainWindowController *mainWindowController; // @synthesize mainWindowController=_mainWindowController;
- (id)getPurchaseLink;
- (id)appPrice;
- (void)getCurrentAppPrice;
- (void)deliverNoticeWithText:(id)arg1;
- (BOOL)userNotificationCenter:(id)arg1 shouldPresentNotification:(id)arg2;
- (long long)copyrightComplianceOfThirdParty;
- (void)creatingFilesOfLogging;
- (void)saveInLogFile:(id)arg1;
- (void)logoutOfYoutube;
- (void)checkingLoginToYouTube;
- (void)showOfferReminderWindow;
- (void)showDemoReminderWindow;
- (void)showWelcomeScreen;
- (void)clearQueuedDownloads:(id)arg1;
- (void)clearSavedDownloads:(id)arg1;
- (void)clearAllDownloads:(id)arg1;
- (void)clickedCancelButton:(id)arg1;
- (long long)showAlertClearDownloadsList;
- (void)menuHelpAiry:(id)arg1;
- (void)menuShowAboutWindow:(id)arg1;
- (void)menuClearListDownloads:(id)arg1;
- (void)menuStartDownload:(id)arg1;
- (void)menuActivate:(id)arg1;
- (void)menuBuyNow:(id)arg1;
- (void)menuLoginOfYoutube:(id)arg1;
- (void)menuIntegratedIntoBrowser:(id)arg1;
- (void)menuShowPreferencesWindow:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)reduceMainWindowSize;
- (void)increaseMainWindowSize;
- (unsigned long long)currentlyNumberOfQueued;
- (unsigned long long)currentlyNumberOfSuspended;
- (unsigned long long)currentlyNumberOfActive;
- (void)blockLoadingLinks;
- (BOOL)haveSavedItems;
- (BOOL)haveItemsQueuedOrSuspended;
- (void)removeAllActiveDownloadsAndReduceWindowSize:(BOOL)arg1;
- (void)removeAllNonActiveDownloads;
- (void)removeAllQueuedAndSuspendedDownloads;
- (void)removeAllQueuedDownloads;
- (void)removeAllBlockedDownloads;
- (void)removeAllSavedDownloads;
- (void)removeAllUnsavedDownloads;
- (id)getItemByConnection:(id)arg1 typeOfItem:(int *)arg2;
- (void)cancelOfDownloadOfItem:(id)arg1 kindOf:(int)arg2;
- (void)saveDownloadsInUserDefaults;
- (void)getListOfDownloadableVideos;
- (void)setNumberFreeDownloads:(long long)arg1;
- (long long)getNumberFreeDownloads;
- (void)showAlertNeedReactivation;
- (void)activationFailedFor:(id)arg1 withError:(int)arg2;
- (void)activationSuccessful:(id)arg1;
- (void)activate;
- (void)applicationWillTerminate:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)handleGetURLEvent:(id)arg1 withReplyEvent:(id)arg2;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSString *installSource; // @dynamic installSource;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

