//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EPYoutubeHelper : NSObject
{
    NSString *pathToLogFile;
    BOOL enableLog;
    NSString *cookies;
}

+ (void)globalCleaning;
+ (void)globalInitialization;
@property(retain, nonatomic) NSString *cookies; // @synthesize cookies;
@property(nonatomic) BOOL enableLog; // @synthesize enableLog;
@property(retain, nonatomic) NSString *pathToLogFile; // @synthesize pathToLogFile;
- (id)errorDescription:(long long)arg1;
- (id)getAllLinksForDownloadsOfVideo:(id)arg1;
- (id)getAllURLsInPlaylistOrChannel:(id)arg1;
- (id)init;

@end

